Allow  logout
AndyClausen/yarn-plugin-gcp-auth pull request #7
Opened 2024-04-06 17:43 UTC by webervin

Simple implementation of https://github.com/AndyClausen/yarn-plugin-gcp-auth/issues/6

2024-04-07 16:51 UTC, AndyClausen commented
Could you document this in the readme as well?

2024-04-08 17:27 UTC, webervin commented
I ammended commit to include some README changes, but seems force pushing to my branch does not play nicelly with PR. Should I create new PR instead now?

2024-04-20 22:00 UTC, AndyClausen requested changes

2024-04-20 22:00 UTC, AndyClausen commented on README.md
> +- `yarn gcp-auth logout`: clears plugin cache, helps ensured no token left in the system.
```suggestion
- `yarn gcp-auth logout`: clears plugin cache to ensure no token is left in the system.
```

2024-04-21 16:08 UTC, AndyClausen approved these changes
Sorry for the wait, looks good :)

2024-04-21 16:12 UTC, merged